# Generated by Django 4.1.3 on 2022-11-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pass_phrase',
            field=models.CharField(blank=True, default='elite+sway+random', max_length=100, null=True),
        ),
    ]
