# Generated by Django 4.1.3 on 2022-11-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('ticket_id', models.CharField(max_length=15)),
                ('topic', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=25)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
    ]
