# Generated by Django 4.1.3 on 2022-11-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0002_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
