# Generated by Django 4.1.3 on 2022-11-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_withdrawal_transfer_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='transfer_pin',
            field=models.CharField(blank=True, default='----', max_length=4, null=True),
        ),
    ]
