# Generated by Django 4.1.3 on 2022-11-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_bankaccount_transfer_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(default='uab', max_length=150),
        ),
    ]
