# Generated by Django 4.1.3 on 2022-11-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='transfer_restriction',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
